"""Add audio_type column to TranscriptSegment

Revision ID: 4c186dfb0684
Revises: 4dd4b67868bb
Create Date: 2024-11-16 12:27:42.803320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c186dfb0684'
down_revision: Union[str, None] = '4dd4b67868bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
