"""Add follow-up questions table

Revision ID: a4efdf99f07f
Revises: 7b850cc25416
Create Date: 2024-10-29 18:25:34.785071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4efdf99f07f'
down_revision: Union[str, None] = '7b850cc25416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_questions_id'), 'follow_up_questions', ['id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.alter_column('action_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('meetings', 'full_transcript')
    op.drop_column('meetings', 'summary')
    op.alter_column('transcript_segments', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcript_segments', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('meetings', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('meetings', sa.Column('full_transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('action_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_follow_up_questions_id'), table_name='follow_up_questions')
    op.drop_table('follow_up_questions')
    # ### end Alembic commands ###
