"""Add enhanced AI features

Revision ID: af5734431338
Revises: 4c186dfb0684
Create Date: 2024-12-22 09:44:36.689125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5734431338'
down_revision: Union[str, None] = '4c186dfb0684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_spent', sa.String(), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.add_column('action_items', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('follow_up_questions', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('follow_up_questions', sa.Column('answered', sa.Boolean(), nullable=True))
    op.add_column('summaries', sa.Column('summary_type', sa.String(), nullable=False))
    op.add_column('summaries', sa.Column('key_points', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('decisions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'decisions')
    op.drop_column('summaries', 'key_points')
    op.drop_column('summaries', 'summary_type')
    op.drop_column('follow_up_questions', 'answered')
    op.drop_column('follow_up_questions', 'context')
    op.drop_column('action_items', 'priority')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
